name: tests

on:
- push
- pull_request

jobs:
  test:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        platform: [ubuntu-latest, macos-latest]
        python:
        - version: "3.9"
          toxenv: py39
        - version: "3.10"
          toxenv: py310
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python.version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python.version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
        pip install ".[dev]"

    - name: Test with tox ${{ matrix.python.toxenv }}
      env:
        TOXENV: ${{ matrix.python.toxenv }}
      run: tox

    - name: Report coverage
      if: matrix.python.version == '3.8'
      run: |
        coverage combine
        coverage report
        coverage xml

    - name: Upload coverage to Codecov  
      if: matrix.python.version == '3.8'
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: GitHub
